mcpServers:
  neo4j-robokop:
    command: uvx
    args:
      - mcp-neo4j-cypher@0.2.1
    env:
      NEO4J_URI: bolt://robokopkg.renci.org:7687
      NEO4J_DATABASE: neo4j

robokopServertool:
  command: uvx
  args:
    - mcp-server-git
