[project]
name = "robokopmcp"
version = "0.1.0"
description = "ROBOKOP CLIENT/SERVER MCP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.0",
    "openai",
    "python-dotenv==1.1.0",
    "pytest"
]

[project.optional-dependencies]
dev = [
    "pytest-asyncio"
]

[tool.pytest.ini_options]
addopts = "-ra"
markers = [
    "asyncio: mark test as async"
]
